.github/workflows/build_desktop.yml

Still use system python, but let UV do it's thing.

Add a more "UV" like build system for desktop apps

---

app/desktop/desktop.py

Let it exit gracefully.
Note, this did not resolve: https://github.com/pyinstaller/pyinstaller/issues/8866

Remove exit call

---

README.md

This PR fixes a typo in the hyperlink to the REST API documentation in the README, which was causing it to lead to a 404.

chore: fix typo in hyperlink leading to 404

---

libs/core/kiln_ai/datamodel/__init__.py
libs/core/kiln_ai/datamodel/basemodel.py
libs/core/kiln_ai/datamodel/test_example_models.py
libs/core/kiln_ai/datamodel/test_model_perf.py

Big perf improvement (30x) on loading our TaskRun datamodel from disk… All the slowness was the JSON schema validation, which we only need to run when changing, not loading.
Added benchmark (may need to adjust the CI limit, but 8k/s on Macbook).
Used profiler for first time - see notes on how to use cprofile

Big perf improvement (30x) 

---

libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py

This PR disables escaping unicode characters into ASCII in the structured output formatter which seemed to be causing unicode characters to be passed on to OpenAI as escaped strings in toolcall arguments during fine-tuning. Additionally adds some tests to demonstrate the issue - the newly added tests fail when `ensure_ascii=False` is not present.
Follow up on: https://github.com/Kiln-AI/Kiln/commit/daf18e62ac87821c23437a1e9c5d0eee8cb1bf29
Fixes: https://github.com/Kiln-AI/Kiln/issues/95 - as it pertains to escaping unicode in structured output arguments.
As illustrated in this [comment](https://github.com/Kiln-AI/Kiln/issues/95#issuecomment-2581395722), fine-tuning jobs for Structured Output tasks currently appear to use up many more `Trained tokens` on OpenAI when the arguments are …

fix: unicode is escaped in structured output

---

libs/core/kiln_ai/adapters/prompt_builders.py
libs/core/kiln_ai/adapters/test_prompt_builders.py

This PR fixes a bug where Unicode characters in structured output are passed back as escaped ASCII literals in the repair prompt. Since the structured output being repaired is serialized into a string, the LLM does not decode it and instead consumes the escape literals rather than the actual characters.
As LLMs have some understanding of escape sequences, this bug breaks the repair output in semi-sporadic, subtle and unpredictable ways - for example, it may inject random characters (often newlines) into the repaired output, or respond with escape sequences instead of the characters.
This is part of a broader issue related to unicode escaping: https://github.com/Kiln-AI/Kiln/issues/95
I, @leonardmq, confirm that I have read and agree to the [Contributors License …

fix: unicode converted into escape sequences in repair prompt

---

libs/core/kiln_ai/adapters/base_adapter.py
libs/core/kiln_ai/adapters/test_saving_adapter_results.py

Fix a bug where Unicode in structured `input` and `output` is escaped in the `BaseAdapter`, causing two main issues:
1. Structured `input` and `output` are sent back to the frontend as escaped strings ([code reference](https://github.com/leonardmq/Kiln/blob/be9d0d6b311d3072aa210d5b16357534036d7d0f/libs/server/kiln_server/run_api.py#L98)), which are displayed as-is in the `Datasets` page.
2. Structured `input` and `output` are persisted in `.kiln` files as ASCII. While valid JSON, this is not ideal for scenarios like collaboration, committing datasets to GitHub, and searching. Additionally, there is a risk of improperly decoding these strings.
After this fix, Kiln will store structured `input` and `output` without escaping Unicode, which is already the behavior for plain text `input` and …

fix: escaped Unicode in BaseAdapter

---

libs/core/kiln_ai/adapters/data_gen/data_gen_task.py
libs/core/kiln_ai/adapters/data_gen/test_data_gen_task.py

This PR fixes:
- bug: a task with structured input will have its schema ASCII-escaped in the sample input generation task (due to `list_json_schema_for_task`), which would cause issues if the schema contains Unicode characters
- test: two existing tests had seemingly contradictory naming, and one test seemed to accidentally be setting `output_json_schema = None` instead of `input_json_schema = None`
Part of a group of bugs caused by escaped Unicode: https://github.com/Kiln-AI/Kiln/issues/95
This seems like this was the last unicode-related issue I found - the remaining `json.dumps` are not serializing user-supplied data that could contain non-ASCII.
This seems
I, @leonardmq, confirm that I have read and agree to the [Contributors License …

fix: unicode in list_json_schema_for_task

---

libs/core/kiln_ai/datamodel/basemodel.py
libs/core/kiln_ai/datamodel/test_models.py

This PR allows Kiln to save and load project, and task information containing Unicode characters (on Windows).
Fixes #116 
I, @bvqbao, confirm that I have read and agree to the [Contributors License Agreement](https://github.com/Kiln-AI/Kiln/blob/main/CLA.md).

fix: unicode in models

---

app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/fine_tune/[finetune_id]/+page.svelte

Fireworks.ai has moved their fine-tuning job detail page under a `v1/` prefix. The link shown in the Fine Tune detail page for a Fireworks.ai fine-tune job in the Kiln dashboard now leads to a 404.
- fixes: https://github.com/Kiln-AI/Kiln/issues/127

fix: fireworks.ai URL has changed

---

app/EULA.md

Adding Two Clarifying Statements to the EULA
*Personal Note:* These statements are purely for clarification; we are not removing or altering any existing policies. We have never claimed ownership of dataset, and local dataset files have never been classified as "Contributions." This update is simply to clarify our existing policy, ensuring that users understand that local dataset is not considered a "Contribution." The "Contribution" section pertains only to information users choose to send us; currently this only includes subscribing to our email list, or giving us feedback on Github/email/etc.
I hope folks can appreciate of our local-first, privacy-focused design, which ensures that we do not have access to datasets by any means. We hope this addresses any concerns raised by Reddit …

Improve EULA for clarity

---

libs/core/kiln_ai/adapters/adapter_registry.py
libs/core/kiln_ai/adapters/model_adapters/openai_model_adapter.py
libs/core/kiln_ai/adapters/provider_tools.py
libs/core/kiln_ai/adapters/test_provider_tools.py
libs/core/kiln_ai/datamodel/model_cache.py

Now they use the correct adapter (OpenAI for OpenAI fine-tunes or custom models, etc)
Improve fine-tune cache.

Make custom models and fine-tunes work in our new adapter regsitry

---

libs/core/kiln_ai/adapters/adapter_registry.py
libs/core/kiln_ai/adapters/model_adapters/langchain_adapters.py
libs/core/kiln_ai/adapters/model_adapters/openai_compatible_config.py
libs/core/kiln_ai/adapters/model_adapters/openai_model_adapter.py
libs/core/kiln_ai/adapters/model_adapters/test_langchain_adapter.py
libs/core/kiln_ai/adapters/provider_tools.py
libs/core/kiln_ai/adapters/test_provider_tools.py
libs/core/pyproject.toml
uv.lock

Also separate concepts of KilnModelProviders (what’s supported by a model) and adapter config/set (keys, urls, etc).

Use OpenAPICompatible adapter for openai compatible models.

---

.github/workflows/windows_release_build.yml

This guide is the way. [[Code Signing With Azure Trusted Signing on GitHub Actions](https://www.hendrik-erz.de/post/code-signing-with-azure-trusted-signing-on-github-actions)](https://www.hendrik-erz.de/post/code-signing-with-azure-trusted-signing-on-github-actions)
Azure docs and UX are no good awful bad.

Create signed windows builds via CI action

---

.github/workflows/build_desktop.yml

This should help the binary be more broadly compatible.

Specify older ubuntu builder for desktop, to link against older libc

---

app/desktop/studio_server/eval_api.py
app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/+page.svelte
app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/create_eval_config/+page.svelte
libs/core/kiln_ai/adapters/eval/g_eval.py
libs/core/kiln_ai/adapters/eval/test_g_eval.py
libs/core/kiln_ai/datamodel/eval.py
libs/core/kiln_ai/datamodel/test_eval_model.py

- Want the evaluator to have some context on what the goal is.
- Don't want to give it the prompt, as we're testing prompts, so it's biasing the evaluator
- Instead, give a short task-desription, which is locked across the eval_config, so no bias for a given prompt.

Okay: fix the root of my 2 prompt issue

---

app/web_ui/src/routes/(app)/dataset/[project_id]/[task_id]/[run_id]/run/+page.svelte
app/web_ui/src/routes/(app)/run/run.svelte

Follow up on https://github.com/Kiln-AI/Kiln/pull/254 which partially resolved the issue preventing the repair UI from working on `file_import` runs. However, additional downstream issues were discovered.
This PR disables the repair UI for runs that are neither `synthetic` nor `human`. Instead of an unusable repair form, users will see a warning indicating that repair is unavailable. Even if this UI is replaced later with a working repair UI, this PR already improves the current behavior. This PR also hides the empty fields in the run `Parameters` block in the sidebar.
The warning is only displayed if the user has rated the run `< 5 stars`. The rationale for showing a warning rather than nothing is that users are more likely to report repairing imported runs as a feature they need if they …

fix: hide repair for imported runs

---

app/desktop/studio_server/finetune_api.py
app/desktop/studio_server/test_finetune_api.py
libs/core/kiln_ai/adapters/fine_tune/base_finetune.py
libs/core/kiln_ai/adapters/fine_tune/fireworks_finetune.py
libs/core/kiln_ai/adapters/fine_tune/test_base_finetune.py
libs/core/kiln_ai/adapters/fine_tune/test_fireworks_tinetune.py
libs/core/kiln_ai/adapters/ml_model_list.py

Allow fine-tuning and easily using over 60 LLMs with fireworks
- Dynamically fetch the list of available models
- Add FW on-demand deployment server support to Kiln, including checking for existing deploys before deploying
- Configure servers for scale-to-zero after 5 mins, making them reasonable cost and dev-ex

Fireworks Fine-tuning: all model support

---

app/desktop/studio_server/repair_api.py
app/desktop/studio_server/test_repair_api.py
app/web_ui/src/lib/utils/form_container.svelte
app/web_ui/src/routes/(app)/run/output_repair_edit_form.svelte
app/web_ui/src/routes/(app)/run/run.svelte
libs/core/kiln_ai/datamodel/task_run.py
libs/core/kiln_ai/datamodel/test_example_models.py

This PR adds support for manually editing a task run repair. After `Attempt repair`, the user has a new button (`Edit`) that turns the repair output display into a text area that allows users editing the repair attempt.
This PR also fixes the missing validation of the repair output in the repair API. There was a bug that allowed repair outputs that do not match the structured output schema, which might have caused downstream problems due to corrupt shapes.
This is an acceptable solution but it has a major limitation due to requiring the user to first `Attempt (automatic) repair`. In the case of a `TaskRun` accessed from the `Dataset` page, the user does not have the ability to select the model used during the repair - it is by default the same as the one that generated the original run …

feat: allow manual repair edit

---

app/web_ui/src/routes/(app)/run/run.svelte

The message under `Repair Output` should be specific to the repair source (`human` or `synthetic`).
UI when the run was manually repaired:
UI when the run was repaired by the model:
Tangential to https://github.com/Kiln-AI/Kiln/issues/115

fix: repaired run message should be source-specific

---

app/web_ui/src/routes/(app)/generate/[project_id]/[task_id]/generate_samples_modal.svelte
app/web_ui/src/routes/(app)/generate/[project_id]/[task_id]/generated_data_node.svelte

- Add `Add to all` buttons on the `Synthetic data` page to let the user generate samples for every subtopic leaf descendant of a given topic node; I called that "Cascade mode"
- Add optional parallelization of synthetic data generation when in Cascade mode
The parallelization is inspired by what was done for the `Save all` action; the error handling is similar. Tried to keep the workers' errors mapped to their topic so that if we want, we can later add something to `Try again` and retry only the failed topics.
https://github.com/Kiln-AI/Kiln/issues/142

feat: synthetic data generation cascade down topic tree

---

app/web_ui/src/lib/utils/json_schema_editor/json_schema_templates.test.ts
app/web_ui/src/lib/utils/json_schema_editor/json_schema_templates.ts

Remove the `raw_schema` introduced in https://github.com/Kiln-AI/Kiln/pull/286 because it is now unused.
N/A

chore: clean up unused raw_schema in UI

---

libs/core/kiln_ai/adapters/parsers/r1_parser.py
libs/core/kiln_ai/adapters/parsers/test_r1_parser.py

The `output` and `intermediate_outputs.reasoning` from thinking models from `together_ai` and possibly other providers come with leading and / or trailing newlines. 
This PR `strip()` both `output` and `intermediate_outputs.reasoning` in the R1 parser.
Example raw data for such a `Run` using `DeepSeek R1 Distill Qwen 32B` on `together_ai`:
```json
{
"v": 1,
"id": "XXX",
"input": "What is your name?",
"output": {
"v": 1,
"id": "XXX",
...
"output": "\n\nMy name is Bob",
"source": {
"type": "synthetic",
"properties": {
"adapter_name": "kiln_openai_compatible_adapter",
"model_name": "deepseek_r1_distill_qwen_32b",
"model_provider": "together_ai",
"prompt_id": "simple_prompt_builder"
}
},
...
},
...
"intermediate_outputs": {
"reasoning": "\nOkay the user is asking for my name.\n"
},
"tags": [ …
```

fix: newlines in together_ai thinking output

---

app/web_ui/src/lib/utils/form_element.svelte

Workaround:
- add `data-op-ignore="true"` field on `FormElement` text input to prevent 1password from overlaying its buttons on top of form fields contained in modals that are present in the DOM but not visible.
A cleaner fix would be to remove the `dialog` from the DOM when not shown, but this workaround should be sufficient for now.
Fixes: https://github.com/Kiln-AI/Kiln/issues/298

fix: disable 1password on text input field

---

checks.sh
utils/pre-commit-hook

It should run everything regardless of what's staged, and the pre-commit hook can specify an option to go faster by only looking at staged.

Improve our checks.sh script. 

---

app/web_ui/src/lib/ui/fancy_select.svelte

Limit max lines in fancy select
