Kiln-AI/Kiln

- app/desktop/studio_server/provider_api.py
- app/desktop/studio_server/test_provider_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/fine_tune/[finetune_id]/+page.svelte
- app/web_ui/src/routes/(app)/run/available_models_dropdown.svelte
- libs/core/kiln_ai/adapters/adapter_registry.py
- libs/core/kiln_ai/adapters/fine_tune/openai_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_openai_finetune.py
- libs/core/kiln_ai/adapters/ml_model_list.py
- libs/core/kiln_ai/datamodel/__init__.py
- libs/core/kiln_ai/datamodel/registry.py
- libs/core/kiln_ai/datamodel/test_registry.py
- libs/server/kiln_server/project_api.py
- List them in available_models
- Look them up when loading adapter
- add model ID to the datamodel
- UI for everything
> Fine tunes working end to end!

- app/web_ui/src/routes/(app)/run/available_models_dropdown.svelte
- libs/core/kiln_ai/adapters/ml_model_list.py
> New models 2024-12-4

- app/desktop/studio_server/finetune_api.py
- app/desktop/studio_server/test_finetune_api.py
- libs/core/kiln_ai/adapters/provider_tools.py
- libs/core/kiln_ai/datamodel/basemodel.py
- libs/core/kiln_ai/datamodel/model_cache.py
- libs/core/kiln_ai/datamodel/test_basemodel.py
- libs/server/kiln_server/run_api.py
- libs/server/kiln_server/task_api.py
- libs/server/kiln_server/test_run_api.py
A faster "find by ID" option using the cache.
> Perf Part 2: Find by ID

- app/web_ui/src/lib/utils/form_element.svelte
- app/web_ui/src/lib/utils/json_schema_editor/json_schema_form_element.svelte
- app/web_ui/src/routes/(fullscreen)/setup/(setup)/create_task/schema_section.svelte
JSON schema UI
https://github.com/Kiln-AI/Kiln/discussions/96#discussioncomment-11719364
> New UI to allow using JSON schema directly when setting a task.

- app/desktop/studio_server/finetune_api.py
- app/desktop/studio_server/test_finetune_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/create_finetune/+page.svelte
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/datamodel/__init__.py
Vertex AI Format for downloads, and 80/10/10 splits
> Vertex AI Format for downloads, and 80/10/10 splits

- guides/Fine Tuning LLM Models Guide.md
I, @<your-github-username>, confirm that I have read and agree to the [Contributors License Agreement](https://github.com/Kiln-AI/Kiln/blob/main/CLA.md).
> Update Fine Tuning LLM Models Guide.md

- app/web_ui/package-lock.json
- app/web_ui/package.json
> Dependancies update

- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/create_finetune/+page.svelte
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/fireworks_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/openai_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/test_fireworks_tinetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_openai_finetune.py
- libs/core/kiln_ai/adapters/ml_model_list.py
- libs/core/kiln_ai/adapters/provider_tools.py
- libs/core/kiln_ai/adapters/test_provider_tools.py
- libs/core/kiln_ai/datamodel/__init__.py
> Use OpenAI's structured response format for structured data

- app/desktop/studio_server/finetune_api.py
- app/desktop/studio_server/test_finetune_api.py
- app/web_ui/src/lib/ui/info_tooltip.svelte
- app/web_ui/src/lib/utils/form_element.svelte
- app/web_ui/src/routes/(app)/run/run.svelte
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py
- libs/core/kiln_ai/adapters/model_adapters/base_adapter.py
- libs/core/kiln_ai/adapters/model_adapters/langchain_adapters.py
- libs/core/kiln_ai/adapters/model_adapters/openai_model_adapter.py
- libs/core/kiln_ai/adapters/model_adapters/test_langchain_adapter.py
- libs/core/kiln_ai/adapters/prompt_builders.py
Add fine-tuning support for thinking/chain-of-thought message chains. Works with R1 style thinking models, basic COT, and custom COT.
> Thinking sft

- app/desktop/studio_server/finetune_api.py
- app/desktop/studio_server/test_finetune_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/create_finetune/+page.svelte
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/fine_tune/[finetune_id]/+page.svelte
- libs/core/kiln_ai/adapters/fine_tune/base_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/fireworks_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/openai_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_base_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/test_fireworks_tinetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_openai_finetune.py
- libs/core/kiln_ai/datamodel/__init__.py
- libs/core/kiln_ai/datamodel/test_models.py
for building inference time compute models
> Support a custom COT instruction for fine tuning

- app/web_ui/src/lib/ui/warning.svelte
- app/web_ui/src/routes/(app)/run/+page.svelte
- app/web_ui/src/routes/(app)/run/available_models_dropdown.svelte
- libs/core/kiln_ai/adapters/prompt_builders.py
- libs/core/kiln_ai/adapters/test_prompt_builders.py
- libs/core/kiln_ai/datamodel/__init__.py
When you select a fine-tune, it automatically uses the right prompt from the data model. Using another prompt will warn you about the risk.
> Really nice UX for fine-tune prompts. 

- app/desktop/studio_server/finetune_api.py
- app/desktop/studio_server/test_finetune_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/create_finetune/+page.svelte
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py
- libs/core/kiln_ai/datamodel/__init__.py
- libs/core/kiln_ai/datamodel/test_dataset_split.py
- libs/core/kiln_ai/datamodel/test_models.py
for training thinking models, at dataset creation time.
> Add the ability to filter datasets to "has intermediate data" 

- app/web_ui/package-lock.json
- app/web_ui/package.json
to attempt a fix to https://github.com/Kiln-AI/Kiln/issues/158
> Update svelte dependencies 

- app/web_ui/src/lib/ui/info_tooltip.svelte
- app/web_ui/src/routes/(app)/generate/[project_id]/[task_id]/+page.svelte
- app/web_ui/src/routes/(app)/settings/providers/add_models/+page.svelte
Make data gen 25x faster, with simple parallelism
> Fast data gen

- app/desktop/studio_server/webhost.py
It's a windows issue, but forcing it to use the correct types fixes it and doesn't hurt.
> Fix a report of win-11 issues with bad mime types. 

- libs/core/kiln_ai/adapters/eval/base_eval.py
- libs/core/kiln_ai/adapters/eval/eval_runner.py
- libs/core/kiln_ai/adapters/eval/g_eval.py
- libs/core/kiln_ai/adapters/eval/test_base_eval.py
- libs/core/kiln_ai/adapters/eval/test_eval_runner.py
- libs/core/kiln_ai/adapters/eval/test_g_eval.py
- libs/core/kiln_ai/adapters/test_prompt_builders.py
- libs/core/kiln_ai/datamodel/eval.py
- libs/core/kiln_ai/datamodel/task.py
- libs/core/kiln_ai/datamodel/test_eval_model.py
- libs/core/kiln_ai/datamodel/test_task.py
Able to run an evaluation.
Includes:
- fancy async concurrency
- Storing results to our model
- New model for storing results
- Progressive runs: restart any job for missing data, or added data
> Evals runner

- app/desktop/studio_server/eval_api.py
- app/desktop/studio_server/test_eval_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/lib/stores.ts
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/+page.svelte
- app/web_ui/src/routes/(app)/prompts/[project_id]/[task_id]/saved/[prompt_id]/+page.svelte
- app/web_ui/src/routes/(app)/run/prompt_type_selector.svelte
- libs/core/kiln_ai/adapters/eval/g_eval.py
- libs/core/kiln_ai/adapters/eval/test_eval_runner.py
- libs/core/kiln_ai/adapters/eval/test_g_eval.py
- libs/core/kiln_ai/adapters/model_adapters/langchain_adapters.py
- libs/core/kiln_ai/adapters/model_adapters/openai_model_adapter.py
- libs/core/kiln_ai/adapters/model_adapters/test_base_adapter.py
- libs/core/kiln_ai/adapters/prompt_builders.py
- libs/core/kiln_ai/adapters/test_prompt_builders.py
- libs/core/kiln_ai/datamodel/eval.py
- libs/core/kiln_ai/datamodel/prompt.py
- libs/core/kiln_ai/datamodel/prompt_id.py
- libs/core/kiln_ai/datamodel/task.py
- libs/core/kiln_ai/datamodel/test_basemodel.py
- libs/core/kiln_ai/datamodel/test_eval_model.py
- libs/core/kiln_ai/datamodel/test_prompt_id.py
- libs/core/kiln_ai/datamodel/test_task.py
- libs/server/kiln_server/prompt_api.py
- Freeze non-frozen prompts into the task_run, so the evals are consisten
- Expose frozen prompts via prompt UI
> Much better prompt system for evals

- app/desktop/studio_server/provider_api.py
- app/desktop/studio_server/test_provider_api.py
- app/web_ui/src/routes/(fullscreen)/setup/(setup)/connect_providers/connect_providers.svelte
- libs/core/kiln_ai/adapters/adapter_registry.py
- libs/core/kiln_ai/adapters/ml_model_list.py
- libs/core/kiln_ai/adapters/model_adapters/litellm_adapter.py
- libs/core/kiln_ai/adapters/model_adapters/test_litellm_adapter.py
- libs/core/kiln_ai/adapters/provider_tools.py
- libs/core/kiln_ai/utils/config.py
> Hugging face

- libs/core/kiln_ai/utils/test_dataset_import.py
- pyproject.toml
- pytest.ini
- uv.lock
> Parallel tests

- .github/workflows/build_desktop.yml
Our Inno-setup GitHub dependency was deleted. I made a fork, and pointing to that instead.
> Inno setup fix

- app/desktop/studio_server/test_generate_docs.py
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/create_finetune/+page.svelte
- app/web_ui/src/routes/(app)/fine_tune/[project_id]/[task_id]/fine_tune/[finetune_id]/+page.svelte
- libs/core/kiln_ai/adapters/fine_tune/base_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/finetune_registry.py
- libs/core/kiln_ai/adapters/fine_tune/test_base_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/test_dataset_formatter.py
- libs/core/kiln_ai/adapters/fine_tune/test_vertex_finetune.py
- libs/core/kiln_ai/adapters/fine_tune/vertex_finetune.py
- libs/core/kiln_ai/adapters/ml_model_list.py
- libs/core/kiln_ai/adapters/provider_tools.py
- libs/core/kiln_ai/adapters/test_provider_tools.py
- libs/core/pyproject.toml
- uv.lock
Ability to fine-tune gemini models on vertex.
> Vertex AI: Fine Tune Gemini Models

- app/web_ui/src/lib/utils/json_schema_editor/json_schema_templates.test.ts
- app/web_ui/src/lib/utils/json_schema_editor/json_schema_templates.ts
- app/web_ui/src/routes/(app)/run/run_input_form.svelte
This PR adds support for array-type properties in the `Run` UI for Tasks with Structured Input.
Arrays are now entered as raw JSON in a `textarea` field. The client performs minimal validation (checks that the input is valid JSON and that it is an array), then server-side handles the more granular validation of the `items`.
Additionally:
- Introduces `raw_schema` to `SchemaModelProperty`, and show it in the `info_description` tooltip for array fields.
Kept the changes fairly minimal as I figure a more comprehensive UI for complex types might come down the line.
https://github.com/Kiln-AI/Kiln/issues/284
Error on invalid JSON:
Error on invalid array: …
> feat: support array structured input in task run UI

- app/web_ui/src/routes/(fullscreen)/setup/(setup)/create_task/edit_task.svelte
- app/web_ui/src/routes/(fullscreen)/setup/(setup)/create_task/schema_section.svelte
It's confusing (3 sources mentioned this in user interviews).
We let you add these later once you better understand Kiln.
> Usability update: don't ask for requirements when first getting setup.

- app/desktop/studio_server/eval_api.py
- app/desktop/studio_server/test_eval_api.py
- app/web_ui/src/lib/api_schema.d.ts
- app/web_ui/src/lib/stores.ts
- app/web_ui/src/lib/types.ts
- app/web_ui/src/lib/utils/link_builder.ts
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/+page.svelte
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/+page.svelte
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/compare_run_methods/+page.svelte
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/[eval_id]/eval_configs/+page.svelte
- app/web_ui/src/routes/(app)/evals/[project_id]/[task_id]/create_evaluator/+page.svelte
- app/web_ui/src/routes/(app)/run/rating.svelte
- app/web_ui/src/routes/(app)/run/run.svelte
- libs/core/kiln_ai/datamodel/task_output.py
- libs/server/kiln_server/run_api.py
- libs/server/kiln_server/task_api.py
- libs/server/kiln_server/test_run_api.py
- libs/server/kiln_server/test_task_api.py
Show eval rating outputs on dataset items.
> Evals: rate anything

- .github/workflows/format_and_lint.yml
> Try a faster misspell setup, go install is much too slow

- libs/core/kiln_ai/adapters/ml_model_list.py
- libs/core/kiln_ai/adapters/model_adapters/test_structured_output.py
> Add GLM 4.6
